# RBAC Roles for application services
# Following least-privilege principle - only grant necessary permissions
---
# Role for reading ConfigMaps and Secrets in the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-reader
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
---
# Role for health-checker service to check pod status
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: health-checker-role
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch"]
---
# Role for metrics-collector to access pod metrics
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metrics-collector-role
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: rbac
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
