# ServiceAccount for AWS Load Balancer Controller with IRSA
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: kustomize
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::852140462703:role/AmazonEKSLoadBalancerControllerRole
