# External Secrets configuration for AWS Secrets Manager integration
# This is the recommended approach for EKS clusters
#
# Secret Source (from Terraform RDS module):
#   - Secret Path: demo/pre-prod/database
#   - Secret ARN: arn:aws:secretsmanager:us-east-1:852140462703:secret:demo/pre-prod/database
#   - Available Keys: username, password, engine, host, port, dbname, DATABASE_URL
#
# Prerequisites:
# 1. Install External Secrets Operator:
#    helm repo add external-secrets https://charts.external-secrets.io
#    helm install external-secrets external-secrets/external-secrets \
#      -n external-secrets --create-namespace --set installCRDs=true
#
# 2. Configure IAM Role for Service Account (IRSA) - see iam-policy.yaml and serviceaccount.yaml
#
# 3. Ensure OIDC provider is configured for EKS cluster (demo-pre-prod-cluster)
#
# Reference: https://external-secrets.io/latest/provider/aws-secrets-manager/
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: external-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-sa
---
# ExternalSecret that syncs database credentials from AWS Secrets Manager
# Source: Terraform RDS module at terraform/pre-prod/modules/rds/main.tf
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials-external
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: database-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: devops-agent-demo
          app.kubernetes.io/component: database
  data:
    # Database connection details from AWS Secrets Manager
    # Secret: demo/pre-prod/database (created by Terraform RDS module)
    - secretKey: DB_HOST
      remoteRef:
        key: demo/pre-prod/database
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: demo/pre-prod/database
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: demo/pre-prod/database
        property: dbname
    - secretKey: DB_USER
      remoteRef:
        key: demo/pre-prod/database
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: demo/pre-prod/database
        property: password
    - secretKey: DB_ENGINE
      remoteRef:
        key: demo/pre-prod/database
        property: engine
    - secretKey: DATABASE_URL
      remoteRef:
        key: demo/pre-prod/database
        property: DATABASE_URL
---
# ExternalSecret that syncs Redis credentials from AWS Secrets Manager
# Source: Terraform ElastiCache module at terraform/pre-prod/modules/elasticache/main.tf
#
# Secret Structure (from Terraform):
#   - host: Redis primary endpoint address
#   - port: Redis port (6379)
#   - connection_string: Full connection URL (rediss://host:port)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-credentials-external
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: redis
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: redis-credentials
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: devops-agent-demo
          app.kubernetes.io/component: redis
  data:
    # Redis connection details from AWS Secrets Manager
    # Secret: demo/pre-prod/redis (created by Terraform ElastiCache module)
    - secretKey: REDIS_HOST
      remoteRef:
        key: demo/pre-prod/redis
        property: host
    - secretKey: REDIS_PORT
      remoteRef:
        key: demo/pre-prod/redis
        property: port
    - secretKey: REDIS_URL
      remoteRef:
        key: demo/pre-prod/redis
        property: connection_string
