# ServiceAccount for External Secrets Operator
# This ServiceAccount is used by the SecretStore to authenticate with AWS Secrets Manager
# using IRSA (IAM Roles for Service Accounts)
#
# The ServiceAccount is annotated with the IAM role ARN that grants access to
# the AWS Secrets Manager secret: demo/pre-prod/database
#
# AWS Account ID: 852140462703
# Region: us-east-1
# EKS Cluster: demo-pre-prod-cluster
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: secrets
    app.kubernetes.io/managed-by: external-secrets
  annotations:
    # IAM Role ARN for IRSA - grants access to AWS Secrets Manager
    # This role must have the SecretsManagerReadWrite policy attached
    # and trust the EKS OIDC provider
    eks.amazonaws.com/role-arn: arn:aws:iam::852140462703:role/external-secrets-irsa-role
