# ArgoCD Redis ExternalSecret
# Fetches the Redis password from AWS Secrets Manager
# and creates a Kubernetes Secret for ArgoCD Redis authentication.
#
# Prerequisites:
#   - External Secrets Operator installed
#   - SecretStore 'aws-secrets-manager' configured in this namespace
#   - Secret 'argocd/redis' exists in AWS Secrets Manager with 'password' property
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-redis
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-redis
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: argocd-redis
    creationPolicy: Owner
  data:
    - secretKey: auth
      remoteRef:
        key: argocd/redis
        property: password
