# Product Service Deployment
# Manages product catalog and inventory
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: product-service
    app.kubernetes.io/instance: product-service-pre-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: devops-agent-demo
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: product-service
      app.kubernetes.io/instance: product-service-pre-prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: product-service
        app.kubernetes.io/instance: product-service-pre-prod
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: devops-agent-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8004"
    spec:
      serviceAccountName: backend-sa
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: product-service
          image: 852140462703.dkr.ecr.us-east-2.amazonaws.com/devops-agent-demo-product-service:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8004
              protocol: TCP
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOG_LEVEL
            - name: METRICS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: METRICS_ENABLED
            - name: CACHE_MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: CACHE_MANAGER_URL
            - name: DB_PROXY_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: DB_PROXY_URL
            - name: METRICS_COLLECTOR_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: METRICS_COLLECTOR_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: tmp
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: product-service
                topologyKey: kubernetes.io/hostname
