# ServiceAccount for External Secrets in ArgoCD namespace
# Enables External Secrets Operator to fetch secrets from AWS Secrets Manager
#
# Prerequisites:
#   1. OIDC provider configured for EKS cluster
#   2. IAM role created with trust policy for this ServiceAccount
#   3. IAM policy attached to role with Secrets Manager access for argocd/* secrets
#
# To create the IAM role and policy, run:
#   See iam/argocd-external-secrets-role.tf or create manually with:
#   - Trust policy allowing OIDC provider for argocd namespace
#   - Policy allowing secretsmanager:GetSecretValue for argocd/* secrets
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: argocd
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: external-secrets
    app.kubernetes.io/managed-by: kubectl
  annotations:
    # IRSA annotation - grants access to AWS Secrets Manager
    # NOTE: You need to create this IAM role with appropriate trust policy
    # and permissions to access argocd/* secrets in AWS Secrets Manager
    eks.amazonaws.com/role-arn: arn:aws:iam::852140462703:role/ArgoCD-ExternalSecrets-Role
    # STS regional endpoint for better availability
    eks.amazonaws.com/sts-regional-endpoints: "true"
    description: "ServiceAccount for External Secrets Operator to access AWS Secrets Manager for ArgoCD"
