# ExternalSecret for GitHub Repository SSH Key
# Fetches SSH private key from AWS Secrets Manager and creates
# an ArgoCD-compatible repository secret
#
# AWS Secret: argocd/github-ssh-key
# Property: private_key
#
# The resulting secret follows ArgoCD's repository secret format:
# https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#repositories
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: repo-devops-agent-k8s-demo
  namespace: argocd
  labels:
    app.kubernetes.io/name: repo-secret
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: repository
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: repo-devops-agent-k8s-demo
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          # This label is required for ArgoCD to recognize repository secrets
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        # Repository URL - must match exactly what's used in Application specs
        url: "git@github.com:snirkap/devops-agent-k8s-demo.git"
        # SSH private key from AWS Secrets Manager
        sshPrivateKey: "{{ .sshPrivateKey }}"
        # Repository type
        type: "git"
  data:
    - secretKey: sshPrivateKey
      remoteRef:
        key: argocd/github-ssh-key
        property: private_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
