# ServiceAccounts for application services
# Each service category gets its own ServiceAccount for least-privilege access
---
# ServiceAccount for frontend applications
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: frontend
  annotations:
    # For IRSA (IAM Roles for Service Accounts) on EKS
    # Update with your actual IAM role ARN for frontend services
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/devops-agent-demo-frontend-role
    description: "ServiceAccount for frontend applications (web-ui, admin-dashboard)"
---
# ServiceAccount for API Gateway
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: api-gateway
  annotations:
    description: "ServiceAccount for API Gateway service"
---
# ServiceAccount for backend services
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: backend
  annotations:
    description: "ServiceAccount for backend services (auth, user, product, order, payment, notification)"
---
# ServiceAccount for data processing services
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processing-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: processing
  annotations:
    description: "ServiceAccount for data processing services (event-processor, analytics, report-generator, data-aggregator, image-processor)"
---
# ServiceAccount for infrastructure services
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrastructure-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: infrastructure
  annotations:
    description: "ServiceAccount for infrastructure services (db-proxy, cache-manager, config-service, metrics-collector, queue-monitor, health-checker)"
---
# ServiceAccount for External Secrets Operator
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: external-secrets
  annotations:
    # IRSA annotation for AWS Secrets Manager access
    # Update with your actual IAM role ARN
    # eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/devops-agent-demo-external-secrets-role
    description: "ServiceAccount for External Secrets Operator to access AWS Secrets Manager"
