# Image Processor Deployment
# Processes images (resize, optimize, etc.) - CPU intensive workload
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-processor
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: image-processor
    app.kubernetes.io/instance: image-processor-pre-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: processing
    app.kubernetes.io/part-of: devops-agent-demo
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: image-processor
      app.kubernetes.io/instance: image-processor-pre-prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: image-processor
        app.kubernetes.io/instance: image-processor-pre-prod
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: processing
        app.kubernetes.io/part-of: devops-agent-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8020"
    spec:
      serviceAccountName: processing-sa
      terminationGracePeriodSeconds: 120
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: image-processor
          image: 852140462703.dkr.ecr.us-east-1.amazonaws.com/devops-agent-demo-image-processor:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8020
              protocol: TCP
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOG_LEVEL
            - name: METRICS_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: METRICS_ENABLED
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: PRODUCT_SERVICE_URL
            - name: DB_PROXY_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: DB_PROXY_URL
            - name: METRICS_COLLECTOR_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: METRICS_COLLECTOR_URL
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_URL
            # S3 configuration for image storage
            - name: S3_BUCKET
              value: "devops-agent-images-pre-prod"
            - name: S3_REGION
              value: "us-east-1"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /health
              port: 8020
            initialDelaySeconds: 15
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8020
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 10
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 30"]
      volumes:
        - name: tmp
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: image-processor
                topologyKey: kubernetes.io/hostname
