# ArgoCD Application - dev-no-domain
# Deploys the dev-no-domain overlay with automatic sync and self-healing
#
# Features:
#   - Auto-sync: Automatically applies changes from Git
#   - Self-heal: Reverts manual changes made to live resources
#   - Auto-prune: Removes resources deleted from Git
#   - Retry on failure: Automatic retry with backoff
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-agent-demo-dev
  namespace: argocd
  labels:
    app.kubernetes.io/name: devops-agent-demo-dev
    app.kubernetes.io/part-of: devops-agent-demo
    app.kubernetes.io/component: application
    environment: dev
  # Finalizer ensures proper cleanup of deployed resources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project reference
  project: devops-agent-demo

  # Source repository configuration
  source:
    repoURL: "git@github.com:snirkap/devops-agent-k8s-demo.git"
    targetRevision: HEAD
    path: overlays/dev-no-domain

  # Destination cluster and namespace
  destination:
    server: https://kubernetes.default.svc
    # Namespace is determined by the Kustomize overlay
    namespace: dev

  # Sync policy configuration
  syncPolicy:
    # Automated sync settings
    automated:
      # Automatically apply changes when Git repo changes
      selfHeal: true
      # Automatically delete resources removed from Git
      prune: true
      # Allow sync even when there are no changes (for initial sync)
      allowEmpty: false

    # Sync options
    syncOptions:
      # Create namespace if it doesn't exist
      - CreateNamespace=true
      # Apply out-of-sync resources only
      - ApplyOutOfSyncOnly=true
      # Respect ignore differences annotations
      - RespectIgnoreDifferences=true
      # Server-side apply for better conflict resolution
      - ServerSideApply=true

    # Retry configuration for failed syncs
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  # Ignore differences for fields that change at runtime
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/minReplicas
        - /spec/maxReplicas

  # Health check configuration
  # Uses default health checks - add custom ones if needed

  # Revision history limit
  revisionHistoryLimit: 10
