# Metrics Collector Deployment
# Collects metrics from all services
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-collector
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: metrics-collector
    app.kubernetes.io/instance: metrics-collector-pre-prod
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/part-of: devops-agent-demo
    app.kubernetes.io/managed-by: kubectl
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: metrics-collector
      app.kubernetes.io/instance: metrics-collector-pre-prod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: metrics-collector
        app.kubernetes.io/instance: metrics-collector-pre-prod
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: infrastructure
        app.kubernetes.io/part-of: devops-agent-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
    spec:
      serviceAccountName: infrastructure-sa
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: metrics-collector
          image: 852140462703.dkr.ecr.us-east-1.amazonaws.com/devops-agent-demo-metrics-collector:1.0.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: ENVIRONMENT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: LOG_LEVEL
            - name: DB_PROXY_URL
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: DB_PROXY_URL
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
      volumes:
        - name: tmp
          emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/name: metrics-collector
                topologyKey: kubernetes.io/hostname
