# ServiceAccounts with IRSA (IAM Roles for Service Accounts) annotations
# These ServiceAccounts are configured to assume AWS IAM roles for accessing AWS services
#
# AWS Account ID: 852140462703
# Region: us-east-1
# EKS Cluster: demo-pre-prod-cluster
# Namespace: devops-agent-demo
#
# Prerequisites:
#   1. OIDC provider configured for EKS cluster
#   2. IAM roles created with trust policies (run 02-create-iam-roles.sh)
#   3. IAM policies attached to roles
---
# ServiceAccount for External Secrets Operator
# Access: AWS Secrets Manager (demo/pre-prod/database)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: external-secrets
    app.kubernetes.io/managed-by: kubectl
  annotations:
    # IRSA annotation - grants access to AWS Secrets Manager
    eks.amazonaws.com/role-arn: arn:aws:iam::852140462703:role/devops-agent-demo-external-secrets-role
    # STS regional endpoint for better availability
    eks.amazonaws.com/sts-regional-endpoints: "true"
    description: "ServiceAccount for External Secrets Operator to access AWS Secrets Manager"
---
# ServiceAccount for infrastructure services (db-proxy, cache-manager, etc.)
# Access: AWS Secrets Manager + ElastiCache (if IAM auth enabled)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infrastructure-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: infrastructure
    app.kubernetes.io/managed-by: kubectl
  annotations:
    # IRSA annotation - grants access to Secrets Manager and ElastiCache
    eks.amazonaws.com/role-arn: arn:aws:iam::852140462703:role/devops-agent-demo-infrastructure-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
    description: "ServiceAccount for infrastructure services (db-proxy, cache-manager, config-service, metrics-collector, queue-monitor, health-checker)"
---
# ServiceAccount for processing services (image-processor needs S3)
# Access: S3 bucket (devops-agent-images-pre-prod)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: processing-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: processing
    app.kubernetes.io/managed-by: kubectl
  annotations:
    # IRSA annotation - grants access to S3 for image processing
    eks.amazonaws.com/role-arn: arn:aws:iam::852140462703:role/devops-agent-demo-processing-role
    eks.amazonaws.com/sts-regional-endpoints: "true"
    description: "ServiceAccount for processing services (event-processor, analytics, report-generator, data-aggregator, image-processor)"
---
# ServiceAccount for backend services
# Access: No direct AWS access needed (uses db-proxy and cache-manager)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: backend
    app.kubernetes.io/managed-by: kubectl
  annotations:
    # No IRSA annotation - backend services access AWS through infrastructure services
    description: "ServiceAccount for backend services (auth, user, product, order, payment, notification)"
---
# ServiceAccount for frontend services
# Access: No direct AWS access needed
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: frontend
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "ServiceAccount for frontend applications (web-ui, admin-dashboard)"
---
# ServiceAccount for API Gateway
# Access: No direct AWS access needed
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: devops-agent-demo
  labels:
    app.kubernetes.io/name: devops-agent-demo
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "ServiceAccount for API Gateway service"
